name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  teaclave-client-sdk-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install cmake openssl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH=~/.cargo/bin:$PATH
          rustup default nightly-2020-04-07 && rustup target add aarch64-apple-ios x86_64-apple-ios
      - name: Building Teaclave Client SDK
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libssh2/lib/pkgconfig/"
          export PATH=~/.cargo/bin:$PATH
          cargo install cargo-lipo
          cargo build --manifest-path sdk/rust/Cargo.toml
          cargo build --manifest-path sdk/rust/Cargo.toml --target aarch64-apple-ios
          cargo lipo --manifest-path sdk/rust/Cargo.toml
          cd sdk/swift/TeaclaveClientSDK && xcodebuild -scheme TeaclaveClientSDK
  sim-debug-ubuntu-1804:
    runs-on: ubuntu-18.04
    container: teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1:0.1.3
    steps:
      - uses: actions/checkout@v2
      - name: Setting up $HOME
        run: |
          cp /root/.bashrc $HOME/.bashrc &&
          ln -sf /root/.rustup ~/.rustup &&
          ln -sf /root/.cargo ~/.cargo
      - name: Preparing build system
        run: |
          . ~/.cargo/env &&
          . /opt/sgxsdk/environment &&
          mkdir -p build &&
          cd build &&
          cmake -DCMAKE_BUILD_TYPE=Debug -DSGX_SIM_MODE=ON -DTEST_MODE=ON ..
      - name: Building
        run: |
          . /opt/sgxsdk/environment &&
          . ~/.cargo/env &&
          cd build &&
          make VERBOSE=1
      - name: Run tests and examples
        run: |
          export AS_SPID="00000000000000000000000000000000" &&
          export AS_KEY="00000000000000000000000000000000" &&
          export AS_ALGO="sgx_epid" &&
          export AS_URL="https://api.trustedservices.intel.com:443" &&
          . ~/.cargo/env &&
          cd build &&
          make run-tests
  sim-release-ubuntu-1804:
    runs-on: ubuntu-18.04
    container: teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1:0.1.3
    steps:
      - uses: actions/checkout@v2
      - name: Setting up $HOME
        run: |
          cp /root/.bashrc $HOME/.bashrc &&
          ln -sf /root/.rustup ~/.rustup &&
          ln -sf /root/.cargo ~/.cargo
      - name: Preparing build system
        run: |
          . ~/.cargo/env &&
          . /opt/sgxsdk/environment &&
          mkdir -p build &&
          cd build &&
          cmake -DCMAKE_BUILD_TYPE=Release -DSGX_SIM_MODE=ON -DTEST_MODE=ON ..
      - name: Building
        run: |
          . /opt/sgxsdk/environment &&
          . ~/.cargo/env &&
          cd build &&
          make VERBOSE=1
      - name: Run tests and examples
        run: |
          export AS_SPID="00000000000000000000000000000000" &&
          export AS_KEY="00000000000000000000000000000000" &&
          export AS_ALGO="sgx_epid" &&
          export AS_URL="https://api.trustedservices.intel.com:443" &&
          . ~/.cargo/env &&
          cd build &&
          make run-tests
  format:
    runs-on: ubuntu-18.04
    container: teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1:0.1.3
    steps:
      - uses: actions/checkout@v2
      - name: Setting up $HOME
        run: |
          cp /root/.bashrc $HOME/.bashrc &&
          ln -sf /root/.rustup ~/.rustup &&
          ln -sf /root/.cargo ~/.cargo
      - name: Preparing build system
        run: |
          . ~/.cargo/env &&
          . /opt/sgxsdk/environment &&
          mkdir -p build &&
          cd build &&
          cmake -DRUSTFLAGS="-D warnings" -DTEST_MODE=ON ..
      - name: Checking code format
        run: |
          . /root/.cargo/env &&
          cd build && make check
  lint:
    runs-on: ubuntu-18.04
    container: teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1:0.1.3
    steps:
      - uses: actions/checkout@v2
      - name: Setting up $HOME
        run: |
          cp /root/.bashrc $HOME/.bashrc &&
          ln -sf /root/.rustup ~/.rustup &&
          ln -sf /root/.cargo ~/.cargo
      - name: Preparing build system
        run: |
          . ~/.cargo/env &&
          . /opt/sgxsdk/environment &&
          mkdir -p build &&
          cd build &&
          cmake -DRUSTFLAGS="-D warnings" -DTEST_MODE=ON ..
      - name: Code linting with Clippy
        run: |
          . /opt/sgxsdk/environment &&
          . /root/.cargo/env &&
          cd build && make CLP=1
